name: Azure github actions
on:
  push:
    branches:
      - hello
  pull_request:
    branches:
      - hello
  workflow_dispatch:
env:
  cloud: azure
defaults:
  run:
    shell: bash
jobs:
  
  HelloWorld:
    runs-on: ubuntu-latest
    steps:

      - id: CheckoutRepository
        name: Checkout repository
        uses: actions/checkout@v3

      - id: AzureAuth
        name: Authenticate With Azure
        uses: azure/login@v1
        with:
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

